using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Domain
{
    public class DataFor : GRCBaseDomain
    {
        private decimal jumlah = 0;
        private int jumlahInt = 0;
        private DateTime tanggal = DateTime.Now;
        private string keterangan = string.Empty;
        private string iPAdd = string.Empty;
        private string alamat = string.Empty;
        private string nomorHp = string.Empty;
        private string username = string.Empty;
        private string password = string.Empty;
        private string type = string.Empty;
        private int userID = 0;
        private int point = 0;
        private int lastNumber = 0;
        private string code = string.Empty;
        private int qty = 0;
        private string nomorSJ = string.Empty;
        private string kabupaten = string.Empty;
        private string nama = string.Empty;
        private string deskripsi = string.Empty;
        private string status = string.Empty;
        private string publish = string.Empty;
        private string dalamPersen = string.Empty;
        private DateTime tglMulai = DateTime.Now;
        private DateTime tglAkhir = DateTime.Now;
        private int idGroupBelanja = 0;
        private DateTime? tglMulaiStr = null;
        private DateTime? tglAkhirStr = null;
        private string jumlahStr = string.Empty;
        private string jenisSatuan = string.Empty;
        private string jenisSisi = string.Empty;
        private string grade = string.Empty;
        private string codeCurrency = string.Empty;
        private string sKU = string.Empty;
        private decimal berat = 0;
        private decimal panjang = 0;
        private decimal lebar = 0;
        private decimal tebal = 0;
        private int diskonID = 0;
        private int kategoriID = 0;
        private int idSatuanBerat = 0;
        private int idSatuanUkuran = 0;
        private int idSatuanUnit = 0;
        private int idJenisSisi = 0;
        private int idGrade = 0;
        private int idProduk = 0;
        private int idKategori = 0;
        private int idCurrency = 0;
        private int idDiskon = 0;
        private string images = string.Empty;
        private string imagesThumb = string.Empty;
        private string imagesPublish = string.Empty;
        private string action = string.Empty;
        private decimal hargaNet = 0;
        private decimal diskon = 0;
        private string groupBelanja = string.Empty;
        private string satuanUnit = string.Empty;
        private string satuanUkuran = string.Empty;
        private string satuanBerat = string.Empty;
        private string typePeriode = string.Empty;
        private decimal nilaiKupon = 0;
        private string email = string.Empty;
        private string mobileNo = string.Empty;
        private string userName = string.Empty;
        private string salesmanName = string.Empty;
        private string distributor = string.Empty;
        private string tokoCode = string.Empty;
        private string tokoName = string.Empty;
        private string cord_LA = string.Empty;
        private string cord_LO = string.Empty;
        private string cord_LA_Toko = string.Empty;
        private string cord_LO_Toko = string.Empty;
        private string distributorName = string.Empty;
        private string distributorCode = string.Empty;
        private int distributorId = 0;
        private int salesmanId = 0;
        private string passwordAndro = string.Empty;
        private string usernameAndro = string.Empty;
        private string text = string.Empty;
        private int prioritas = 0;
        private DateTime jadwalKirim = DateTime.Now;
        private string description = string.Empty;
        private int unitID = 0;
        private int unitSalesman = 0;
        private int countReg = 0;
        private int availbleReg = 0;
        private int inboxIdSmsReply = 0;
        private string namaPromo = string.Empty;
        private string modul = string.Empty;
        private string unitSales = string.Empty;
        private string unit = string.Empty;
        private string photo = string.Empty;
        private int page = 0;
        private int row = 0;
        private string surveyorName = string.Empty;
        private int propinsiID = 0;
        private int kabKotaID = 0;
        private string propinsi = string.Empty;
        private string namaKabKota = string.Empty;
        private string idBroadcast = string.Empty;
        private string namaToko = string.Empty;
        private string alamatToko = string.Empty;
        private string location = string.Empty;
        private int salesmanID = 0;
        private int tokoID = 0;
        private string messageText = string.Empty;
        private int bounce = 0;
        private int distID = 0;
        private string city = string.Empty;
        private string distIDStr = string.Empty;
        private string depoID = string.Empty;
        private DateTime periodeOmsetFrom = DateTime.Now;
        private DateTime periodeOmsetTo = DateTime.Now;
        private DateTime periodeKunjunganFrom = DateTime.Now;
        private DateTime periodeKunjunganTo = DateTime.Now;
        private string tokoLeft = string.Empty;
        private decimal omset = 0;
        private int kunjungan = 0;
        private int jmlToko = 0;
        private int jmlTokoDiKunjungi = 0;
        private int jmlTokoDiKunjungi2x = 0;
        private string time = string.Empty;
        private string timeDate = string.Empty;
        private string merk = string.Empty;
        private string jumlahString = string.Empty;
        private string ket1 = string.Empty;
        private string ket2 = string.Empty;
        private decimal pointDecimal = 0;
        private int rank = 0;
        private int forSales = 0;
        private int forSurveyor = 0;
        private int forGrcHelp = 0;
        private int forSalesMkt = 0;
        private int subDistID = 0;
        private string area = string.Empty;
        private string itemsName = string.Empty;
        private string itemsQty = string.Empty;
        private string itemsSatuan = string.Empty;

        public string ItemsName { get { return itemsName; } set { itemsName = value; } }
        public string ItemsQty { get { return itemsQty; } set { itemsQty = value; } }
        public string ItemsSatuan { get { return itemsSatuan; } set { itemsSatuan = value; } }
        public string Area { get { return area; } set { area = value; } }
        public int SubDistID { get { return subDistID; } set { subDistID = value; } }
        public int ForSales { get { return forSales; } set { forSales = value; } }
        public int ForSurveyor { get { return forSurveyor; } set { forSurveyor = value; } }
        public int ForGrcHelp { get { return forGrcHelp; } set { forGrcHelp = value; } }
        public int ForSalesMkt { get { return forSalesMkt; } set { forSalesMkt = value; } }
        public int Rank { get { return rank; } set { rank = value; } }
        public decimal PointDecimal { get { return pointDecimal; } set { pointDecimal = value; } }
        public string Ket1 { get { return ket1; } set { ket1 = value; } }
        public string Ket2 { get { return ket2; } set { ket2 = value; } }
        public string JumlahString { get { return jumlahString; } set { jumlahString = value; } }
        public string Merk { get { return merk; } set { merk = value; } }
        public string TimeDate { get { return timeDate; } set { timeDate = value; } }
        public int JmlToko { get { return jmlToko; } set { jmlToko = value; } }
        public int JmlTokoDiKunjungi { get { return jmlTokoDiKunjungi; } set { jmlTokoDiKunjungi = value; } }
        public int JmlTokoDiKunjungi2x { get { return jmlTokoDiKunjungi2x; } set { jmlTokoDiKunjungi2x = value; } }
        public int Kunjungan { get { return kunjungan; } set { kunjungan = value; } }
        public decimal Omset { get { return omset; } set { omset = value; } }
        public DateTime PeriodeOmsetFrom { get { return periodeOmsetFrom; } set { periodeOmsetFrom = value; } }
        public DateTime PeriodeOmsetTo { get { return periodeOmsetTo; } set { periodeOmsetTo = value; } }
        public DateTime PeriodeKunjunganFrom { get { return periodeKunjunganFrom; } set { periodeKunjunganFrom = value; } }
        public DateTime PeriodeKunjunganTo { get { return periodeKunjunganTo; } set { periodeKunjunganTo = value; } }
        public string TokoLeft { get { return tokoLeft; } set { tokoLeft = value; } }
        public string DepoID { get { return depoID; } set { depoID = value; } }
        public string DistIDStr { get { return distIDStr; } set { distIDStr = value; } }
        public string City { get { return city; } set { city = value; } }
        public int DistID { get { return distID; } set { distID = value; } }
        public int Bounce { get { return bounce; } set { bounce = value; } }
        public string MessageText { get { return messageText; } set { messageText = value; } }
        public int TokoID { get { return tokoID; } set { tokoID = value; } }
        public int SalesmanID { get { return salesmanID; } set { salesmanID = value; } }
        public string Location { get { return location; } set { location = value; } }
        public string AlamatToko { get { return alamatToko; } set { alamatToko = value; } }
        public string NamaToko { get { return namaToko; } set { namaToko = value; } }
        public string IdBroadcast { get { return idBroadcast; } set { idBroadcast = value; } }
        public string SurveyorName { get { return surveyorName; } set { surveyorName = value; } }
        public int Row { get { return row; } set { row = value; } }
        public int Page { get { return page; } set { page = value; } }
        public string Photo { get { return photo; } set { photo = value; } }
        public string Unit { get { return unit; } set { unit = value; } }
        public string UnitSales { get { return unitSales; } set { unitSales = value; } }
        public string Modul { get { return modul; } set { modul = value; } }
        public string NamaPromo { get { return namaPromo; } set { namaPromo = value; } }
        public int InboxIdSmsReply { get { return inboxIdSmsReply; } set { inboxIdSmsReply = value; } }
        public int AvailbleReg { get { return availbleReg; } set { availbleReg = value; } }
        public int CountReg { get { return countReg; } set { countReg = value; } }
        public int UnitID { get { return unitID; } set { unitID = value; } }
        public int UnitSalesman { get { return unitSalesman; } set { unitSalesman = value; } }
        public string Description { get { return description; } set { description = value; } }
        public DateTime JadwalKirim { get { return jadwalKirim; } set { jadwalKirim = value; } }
        public int Prioritas { get { return prioritas; } set { prioritas = value; } }
        public string Text { get { return text; } set { text = value; } }
        public string UsernameAndro { get { return usernameAndro; } set { usernameAndro = value; } }
        public string PasswordAndro { get { return passwordAndro; } set { passwordAndro = value; } }
        public int SalesmanId { get { return salesmanId; } set { salesmanId = value; } }
        public int DistributorId { get { return distributorId; } set { distributorId = value; } }
        public string DistributorCode { get { return distributorCode; } set { distributorCode = value; } }
        public string DistributorName { get { return distributorName; } set { distributorName = value; } }
        public string Cord_LO { get { return cord_LO; } set { cord_LO = value; } }
        public string Cord_LA { get { return cord_LA; } set { cord_LA = value; } }
        public string Cord_LO_Toko { get { return cord_LO_Toko; } set { cord_LO_Toko = value; } }
        public string Cord_LA_Toko { get { return cord_LA_Toko; } set { cord_LA_Toko = value; } }
        public string TokoCode { get { return tokoCode; } set { tokoCode = value; } }
        public string TokoName { get { return tokoName; } set { tokoName = value; } }
        public string Distributor { get { return distributor; } set { distributor = value; } }
        public string SalesmanName { get { return salesmanName; } set { salesmanName = value; } }
        public string UserName { get { return userName; } set { userName = value; } }
        public string MobileNo { get { return mobileNo; } set { mobileNo = value; } }
        public string Email { get { return email; } set { email = value; } }
        public decimal NilaiKupon { get { return nilaiKupon; } set { nilaiKupon = value; } }
        public string TypePeriode { get { return typePeriode; } set { typePeriode = value; } }
        public int IdDiskon { get { return idDiskon; } set { idDiskon = value; } }
        public string SatuanBerat { get { return satuanBerat; } set { satuanBerat = value; } }
        public string SatuanUkuran { get { return satuanUkuran; } set { satuanUkuran = value; } }
        public string SatuanUnit { get { return satuanUnit; } set { satuanUnit = value; } }
        public string GroupBelanja { get { return groupBelanja; } set { groupBelanja = value; } }
        public decimal Diskon { get { return diskon; } set { diskon = value; } }
        public decimal HargaNet { get { return hargaNet; } set { hargaNet = value; } }
        public string Action { get { return action; } set { action = value; } }
        public string ImagesPublish { get { return imagesPublish; } set { imagesPublish = value; } }
        public string ImagesThumb { get { return imagesThumb; } set { imagesThumb = value; } }
        public string Images { get { return images; } set { images = value; } }        
        public int IdKategori { get { return idKategori; } set { idKategori = value; } }
        public int IdProduk { get { return idProduk; } set { idProduk = value; } }
        public int IdGrade { get { return idGrade; } set { idGrade = value; } }
        public int IdJenisSisi { get { return idJenisSisi; } set { idJenisSisi = value; } }
        public int IdSatuanUnit { get { return idSatuanUnit; } set { idSatuanUnit = value; } }
        public int IdSatuanUkuran { get { return idSatuanUkuran; } set { idSatuanUkuran = value; } }
        public int IdSatuanBerat { get { return idSatuanBerat; } set { idSatuanBerat = value; } }
        public int IdCurrency { get { return idCurrency; } set { idCurrency = value; } }
        public int KategoriID { get { return kategoriID; } set { kategoriID = value; } }
        public int DiskonID { get { return diskonID; } set { diskonID = value; } }
        public decimal Tebal { get { return tebal; } set { tebal = value; } }
        public decimal Lebar { get { return lebar; } set { lebar = value; } }
        public decimal Panjang { get { return panjang; } set { panjang = value; } }
        public decimal Berat { get { return berat; } set { berat = value; } }
        public string SKU { get { return sKU; } set { sKU = value; } }
        public string CodeCurrency { get { return codeCurrency; } set { codeCurrency = value; } }
        public string Grade { get { return grade; } set { grade = value; } }
        public string JenisSisi { get { return jenisSisi; } set { jenisSisi = value; } }
        public string JenisSatuan { get { return jenisSatuan; } set { jenisSatuan = value; } }
        public string JumlahStr { get { return jumlahStr; } set { jumlahStr = value; } }
        public DateTime? TglAkhirStr { get { return tglAkhirStr; } set { tglAkhirStr = value; } }
        public DateTime? TglMulaiStr { get { return tglMulaiStr; } set { tglMulaiStr = value; } }
        public int IdGroupBelanja { get { return idGroupBelanja; } set { idGroupBelanja = value; } }
        public DateTime TglAkhir { get { return tglAkhir; } set { tglAkhir = value; } }
        public DateTime TglMulai { get { return tglMulai; } set { tglMulai = value; } }
        public string DalamPersen { get { return dalamPersen; } set { dalamPersen = value; } }
        public string Publish { get { return publish; } set { publish = value; } }
        public string Status { get { return status; } set { status = value; } }
        public string Deskripsi { get { return deskripsi; } set { deskripsi = value; } }
        public string Nama { get { return nama; } set { nama = value; } }
        public string Kabupaten { get { return kabupaten; } set { kabupaten = value; } }
        public string NomorSJ { get { return nomorSJ; } set { nomorSJ = value; } }
        public int Qty { get { return qty; } set { qty = value; } }
        public string Code { get { return code; } set { code = value; } }
        public int LastNumber { get { return lastNumber; } set { lastNumber = value; } }        
        public int Point { get { return point; } set { point = value; } }        
        public int UserID { get { return userID; } set { userID = value; } }        
        public string Username { get { return username; } set { username = value; } }
        public string Password { get { return password; } set { password = value; } }
        public string Type { get { return type; } set { type = value; } }
        public string Alamat { get { return alamat; } set { alamat = value; } }
        public string NomorHp { get { return nomorHp; } set { nomorHp = value; } }
        public string Keterangan { get { return keterangan; } set { keterangan = value; } }
        public string IPAdd { get { return iPAdd; } set { iPAdd = value; } }
        public decimal Jumlah { get { return jumlah; } set { jumlah = value; } }
        public int JumlahInt { get { return jumlahInt; } set { jumlahInt = value; } }        
        public DateTime Tanggal { get { return tanggal; } set { tanggal = value; } }
        public int KabKotaID { get { return kabKotaID; } set { kabKotaID = value; } }
        public int PropinsiID { get { return propinsiID; } set { propinsiID = value; } }
        public string Propinsi { get { return propinsi; } set { propinsi = value; } }
        public string NamaKabKota { get { return namaKabKota; } set { namaKabKota = value; } }
        public string Time { get { return time; } set { time = value; } }
    }
}
